stages:
 - build
#  - test
#  - review
#  - deploy

build-job:
  tags:
    - test
  stage: build
  image: node:16-alpine
  script:
    - cd front
    - npm ci
    - npm run build
    - echo "Project was successfully built."
