stages:
  - build
  # - test
  # - review
  - deploy

build-job:
  tags:
    - test
  stage: build
  image: node:16-alpine
  script:
    - cd front
    - npm ci
    - npm run build
    - echo "Project was successfully built."

deploy-job:
  only:
    - main
  tags:
    - review
  stage: deploy
  variables:
    BACK_PORT: 3087
    FRONT_PORT: 3086
    BACK_URI: https://uwto.dev.zagroza.agency:8080
    FRONT_URI: https://uwto.dev.zagroza.agency
    CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA
    CI_COMMIT_TIMESTAMP: $CI_COMMIT_TIMESTAMP
    CI_COMMIT_TITLE: $CI_COMMIT_TITLE
  script:
    - cp -TRv back-initial-data/ .
    - chmod -R 777 ./back/uploads
    - chmod -R 777 ./back/database
    - chmod -R 777 ./back/extensions
    - docker image prune -f
    - docker compose down
    - docker compose build --no-cache
    - docker compose up -d
